version: '3'

volumes:
  pg_data4:
  static:
  media:

services:
  bd4:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data4:/var/lib/postgresql/data
  backend:
    image: ihnupfidi/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - bd4
  frontend:
    env_file: .env
    image: ihnupfidi/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: ihnupfidi/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    depends_on:
      - backend
    volumes:
      - static:/static
      - media:/media
