version: '3'

volumes:
  pg_data_production:
  static_volume:
  media:

services:
  bd2:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: ihnupfidi/kittygram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media:/var/www/kittygram/media/
  frontend:
    image: ihnupfidi/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  nginx:
    image: ihnupfidi/kittygram_gateway
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
      - media:/var/www/kittygram/media/
    ports:
      - 9000:80